### ISSUE TITLE
Unclear example

### ISSUE THREAD

**Issue by ajraymond** [SmartThingsCommunity/Documentation#123]
From: http://docs.smartthings.com/en/latest/device-type-developers-guide/building-zigbee-device-handlers.html

"The value we are using is formatted in an Unsigned 16-bit integer (0x21) with the payload being in 1/10th of a second. In this case the payload ({1400}) translates to 2 seconds."

How can 1400 translate to 2 seconds if the payload is in 1/10ths of a second?

Thanks

**Comment by unixbeast** [comment]
Hello! I actually had to go to engineering with this question. This is the answer I received:
"The value 1400 is actually a little endian hex string. It translates into an integer value of 0x0014, which is decimal value 20. Finally, 20 * 1/10 of a second equals 2 seconds."

I hope that clears things up for you. I also added a note to the docs with the same response. It should appear shortly.

**Comment by ajraymond** [comment]
Are you sure about that? I think the payload provided to st wattr should not be reversed.

In Centralite Thermostat:

```
def setCoolingSetpoint(degrees) {
	def degreesInteger = degrees as Integer
	log.debug "setCoolingSetpoint({$degreesInteger} ${temperatureScale})"
	sendEvent("name":"coolingSetpoint", "value":degreesInteger)
	def celsius = (getTemperatureScale() == "C") ? degreesInteger : (fahrenheitToCelsius(degreesInteger) as Double).round(2)
	"st wattr 0x${device.deviceNetworkId} 1 0x201 0x11 0x29 {" + hex(celsius*100) + "}"
}
```

hex(20*100) returns the string "7d0" (which is not reversed), not "d007" (which is).

**Comment by unixbeast** [comment]
I went back to the devs on this and it looks like you are correct. This is the response I got:

"the payload is a hex string. The length of the payload most be two times the length of the data type. So the payload for 16-bit datatype should be 4 hex digits, the payload for a 32-bit datatype should be 8 hex digits, etc... Hopefully you can think of a clear way to say that.

You can also tell ajraymond that the Centralite Thermostat code is correct and the {1400} example was not."

So now I will change all of the examples that reference a payload of {1400} to {0014}.
I hope this answers your question.

Dave

**Comment by unixbeast** [comment]
I'm going to close this issue as I have committed the change to the documentation. Let me know if you have any other comments about this!

Dave
