### ISSUE TITLE
ZigBee example refers to CentraLite switch not found in IDE

### ISSUE THREAD

**Issue by ajraymond** [SmartThingsCommunity/Documentation#124]
http://docs.smartthings.com/en/latest/device-type-developers-guide/zigbee-example.html

    An example of a ZigBee device-type is the CentraLite Switch. You can find the code in the IDE in the “Browse Device Types” menu.

I can't find the code for this example in the IDE. Only two devices from CentraLite appear: dimmer and thermostat.

**Comment by unixbeast** [comment]
Thanks for bringing this to attention! Looks like the centralite switch example was changed to SmartPower Outlet. I've updated to docs to reflect this change.
