### ISSUE TITLE
Attribute() requires two args?

### ISSUE THREAD

**Issue by ajraymond** [SmartThingsCommunity/Documentation#136]
The documentation (http://docs.smartthings.com/en/latest/ref-docs/device-handler-ref.html#attribute)
states that the  ``attributeType`` is optional. However, I get the following error if I don't specify it:
```
        attribute "myval"
```
```
groovy.lang.MissingMethodException: No signature of method: script143750118174499637161.attribute() is applicable for argument types: (java.lang.String) values: [myval]
Possible solutions: attribute(java.util.Map), attribute(java.lang.String, java.lang.String), attribute(java.lang.String, java.lang.String, java.util.List), tileAttribute(java.lang.String), attributeState(java.lang.String) @ line 5 
```

which goes away if I force the attribute type:
```
        attribute "myval", "number"
```

Am I missing something?

Thanks

**Comment by unixbeast** [comment]
I think you are correct! Good catch. I've updated the documentation you reference above with the attributeType parameter being required.
