### ISSUE TITLE
wattr payload format

### ISSUE THREAD

**Issue by ajraymond** [SmartThingsCommunity/Documentation#137]
I am implementing a new ZigBee device driver, and it seems like the "st wattr" command expects an hexadecimal payload value without 0x. e.g. {400} is a payload value of hex 0x400 == decimal 1024.

Can you confirm this?

**Comment by ajraymond** [comment]
This page appears to support this finding, at least for the zcl command.
https://community.smartthings.com/t/help-with-sending-zigbee-configure-reporting-command/4121/10

"the payload is automatically in hex so you don't have to use the 0x part of {0x3f800000}. It was probably not getting packed and sent"

**Comment by unixbeast** [comment]
so that is correct. the payload is automatically in hex. But it is little endian. So if you want a decimal value of 1024, it would actually be a payload of {0400}.
