### ISSUE TITLE
Document callback return values

### ISSUE THREAD

**Issue by ajraymond** [SmartThingsCommunity/Documentation#140]
It would be nice to describe/summarize the commands and helpers related to callback return values:
- delayBetween([commands], milliDelay): documented in the z-wave example only (http://docs.smartthings.com/en/latest/device-type-developers-guide/building-z-wave-device-handlers.html?highlight=delaybetween)
- st rattr/wattr/cmd
- zdo bind

Described at https://community.smartthings.com/t/help-with-sending-zigbee-configure-reporting-command/4121/8, but not in the documentation:
- zcl global send-me-a-report
- delay
- send

Others?

**Comment by ajraymond** [comment]
Also, described at https://community.smartthings.com/t/zigbee-device-type-question-about-enrollresponse-and-the-function-configure/9390:
  * raw

**Comment by unixbeast** [comment]
I agree. The ZWave/Zigbee documentation is slated for a major update. We need to both add content and fix content. Work in this area is planned in the next couple of months.
We will pay particular attention to your comment here and make sure we specifically address these areas of concern.

Dave
