### ISSUE TITLE
Hex value instead of decimal

### ISSUE THREAD

**Issue by ajraymond** [SmartThingsCommunity/Documentation#151]
In http://docs.smartthings.com/en/latest/device-type-developers-guide/zigbee-primer.html:

```
An example of a Write Attribute that would set the transition time from on to off of a dimmer look like this:

"st wattr 0x${device.deviceNetworkId} 1 8 0x10 0x21 {1400}”

The 1400 means the light takes 1400 1/10ths of a second to turn on and off.
```

As we've established, 1400 is in fact a hex value.

I would also like to link to Issue #124, for which I haven't received a final answer.

**Comment by unixbeast** [comment]
Oh, good catch. Looks like there were two references to the 1400 value. I'll update this area of the docs with the same comment I added for the other.
As far as issue #124. Were you looking for further information regarding the SmartApp name change?

Thanks,
Dave

**Comment by ajraymond** [comment]
My bad! It was issue #123

**Comment by unixbeast** [comment]
I have made the appropriate changes to the documentation.
