### ISSUE TITLE
Diagram in Device Type Overview page has misdirected arrows

### ISSUE THREAD

**Issue by msparks** [SmartThingsCommunity/Documentation#18]
The arrows between SmartApp and Data Management Layer in the [Device Type Overview documentation](http://docs.smartthings.com/en/latest/device-type-developers-guide/overview.html) have directions opposite what they should be. For example, the Data Management Layer should be reporting normalized statuses to the SmartApp, not the other way around. Similarly, commands come from the app, not to it. The arrows from the Mobile App block are also incorrect.

**Comment by jimmyjames** [comment]
we updated that diagram (it's been moved into the Quick Start section of the guide now).
