### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jho1965us** [SmartThingsCommunity/Documentation#20]
Documentation / device-type-developers-guide / anatomy-of-a-device-type.rst (http://docs.smartthings.com/en/latest/device-type-developers-guide/anatomy-of-a-device-type.html) > Anatomy of a Device Type > Metadat Declaraions > Definitions Metadata
Paragraph 3 link shown as "reference document" pointing to: https://github.com/SmartThingsCommunity/Documentation/blob/master/introduction/what-can-developers-do-with-smartthings/device-type-development/capability-taxonomy.html

following this link shows a "This page does not exists page"

**Comment by jimmyjames** [comment]
This link has been fixed to point to the capability taxonomy.
