### ISSUE TITLE
is enum the correct parameter type for setThermostatFanMode and setThermostatMode?

### ISSUE THREAD

**Issue by StrykerSKS** [SmartThingsCommunity/Documentation#247]
When looking at the capabilities here for a Thermostat: http://docs.smartthings.com/en/latest/capabilities-reference.html is uses enum as the input type for setThermostatFanMode and setThermostatMode. However, it seems that these should really be type String instead since you can only set one mode at a time for each of these.

I can make the changes to the documentation and do the pull request, but wanted to verify that my assumption is correct or not.

**Comment by jimmyjames** [comment]
I think you're right. In the DB that backs the capabilities, it's actually in an enum in the sense that there is a discreet set of possible values. But that means it really can be only one at a time like you found.

The possible values for thermostat mode are: "off","heat","cool","emergency heat","auto"
and for thermostat fan mode: "on","auto","circulate"

Thanks for bringing this to our attention!!!!
