### ISSUE TITLE
resp.data.status.code will never execute with resp.status == 401

### ISSUE THREAD

**Issue by StrykerSKS** [SmartThingsCommunity/Documentation#252]
Based on my testing, the example in http://docs.smartthings.com/en/latest/cloud-and-lan-connected-device-types-developers-guide/building-cloud-connected-device-types/building-the-service-manager.html shown below will never actually execute.

> if (resp.status == 401 && resp.data.status.code == 14) {
>     log.debug "Storing the failed action to try later"
>     def action = "actionCurrentlyExecuting"
>     log.debug "Refreshing your auth_token!"
>     refreshAuthToken()
>     // replay initial request from the action variable
>     retryInitialRequest(action)
> }

It seems that the expected behavior is for any non-200 response to throw an exception (based on my testing) and seems to be also stated in the documentation elsewhere:

Throwing an exception also seems to be the expected behavior according to the docs:
http://docs.smartthings.com/en/latest/smartapp-developers-guide/calling-web-services-in-smartapps.html

> Any ‘failed’ response response will generate an exception, so you should wrap your calls in a try/catch block.

**Comment by jimmyjames** [comment]
Thanks for point that out, that is something we'll have to investigate.
