### ISSUE TITLE
SmartSense Multi, missing properties?

### ISSUE THREAD

**Issue by phae** [SmartThingsCommunity/Documentation#26]
I'm trying to access the "acceleration" value from the SmartSense Multi device, and it doesn't appear to be an available in the API. 

I'm looking at this part of the documentation:

http://docs.smartthings.com/en/latest/smartapp-developers-guide/preferences-and-settings.html?highlight=threeAxisMeasurement 

The API also doesn't seem to return anything for a SmartSense Multi with the "threeAxisMeasurement" property, despite having "threeAxis" in device info.  

Can only seem to actually return contact state and temperature on these devices via the API.

**Comment by CosmicPuppy** [comment]
Not sure this is supposed to be a "discussion thread", but figured I'd paste a quick counter-example to Phae's issue:

This SmartApp code works (ummm... I forget what I used as a base template):

```groovy
def accelerationHandler(evt) {
	def latestThreeAxisState = multisensor.threeAxisState // e.g.: 0,0,-1000
    log.debug latestThreeAxisState.xyzValue.x
    log.debug ','
    log.debug latestThreeAxisState.xyzValue.y
    log.debug ','
    log.debug latestThreeAxisState.xyzValue.z
    log.debug "latestThreeAxisState.xyzValue.z = "
    //log.debug lastestThreeAxisState.xyzValue.z
	if (latestThreeAxisState) {
		def isTripped = Math.abs(latestThreeAxisState.xyzValue.z) < 250 // TODO: Test that this value works in most cases...
        log.debug "isTripped: "
        log.debug isTripped
		def isNotScheduled = state.status != "scheduled"

		if (!isTripped) {
			clearSmsHistory()
			clearStatus()
        } else {
			runIn(1, takeAction, [overwrite: false])
			state.status = "scheduled"
		}
	}
	else {
		log.warn "COULD NOT FIND LATEST 3-AXIS STATE FOR: ${multisensor}"
	}
}
```
