### ISSUE TITLE
Image in Label Preference Type doesn't show up on Android Mobile App

### ISSUE THREAD

**Issue by pstuart** [SmartThingsCommunity/Documentation#261]
http://docs.smartthings.com/en/latest/smartapp-developers-guide/preferences-and-settings.html

Rendering this code:
section("mPower Connect SmartApp") {
    label(name: "labelWithImage",
              title: "This element has an image and a title.",
              description: "image and a title",
              required: false,
              image: "https://ubcdn.co/media/images/product/mpower-pro/mpower-pro-product-model-small.png")
    	paragraph """This mPower Connect SmartApp allows you to enter the IP address of the actual device, not the java controller and your username and password along with the hub this local lan device is connected to.
        Upon install, this SmartApp will install a single Controller Device and 8 virtual Switches representing the state of each outlet."""
    }

results in this screen in Android.  The image does not render as the documentation shows.

![screenshot_20160318-202410](https://cloud.githubusercontent.com/assets/8062718/13895857/6a3ca5e2-ed47-11e5-956f-a02c78790048.png)

**Comment by jimmyjames** [comment]
Verified this is not working correctly on Android, works on iOS. Filed an internal bug, added note to docs in https://github.com/SmartThingsCommunity/Documentation/pull/266
