### ISSUE TITLE
first-smartapp "My Apps" category is not listed

### ISSUE THREAD

**Issue by gvkalra** [SmartThingsCommunity/Documentation#286]
Quoting from [first-smartapp](https://github.com/SmartThingsCommunity/Documentation/blob/master/getting-started/first-smartapp.rst#create-a-smartapp) section:

The documentation suggests to select "My Apps" as the category
> 
> Category
>     SmartApps are categorized based on functionality. This is used by the mobile applications. When publishing SmartApps for your own use (which is what we will be doing), all SmartApps will appear in "My Apps" category. Just to be complete, go ahead and select "My Apps".

However, only below options are available:

> Convenience
> Family
> Fun & Social
> Green Living
> Health & Wellness
> Mode Magic
> Pets
> Safety & Security
> SmartThings Labs

Is the documentation suggesting that my personal application will appear on Mobile as "My Apps" or is it asking me to select "My Apps" in the category? I believe the former is true.

The line "Just to be complete, go ahead and select 'My Apps'." is causing a confusion in understanding.

**Comment by CNG** [comment]
I don't work at SmartThings, but it seemed to me there must have been a reorganization at some point (perhaps an explicit "My Apps" was removed at that point), as the categories in the documentation don't match the categories in the mobile app.

Regardless of what you choose, the app will show under "My Apps" in the mobile app. Perhaps the category has different meaning once published publicly, but for my test I just left the category unselected.

**Comment by CNG** [comment]
This probably doesn't matter, but incidentally, it seems you can still change the category in the IDE to `My Apps` and save just fine without getting an error like:

> java.lang.RuntimeException: Metadata Error: Category 'X' not found

And then the app does indeed show category of "My Apps" in the IDE listing of SmartApps.

**Comment by CNG** [comment]
Since I was stumbling on tons of minor issues, I went ahead and removed that apparently obsolete sentence, @gvkalra, in https://github.com/SmartThingsCommunity/Documentation/pull/288 – perhaps someone from SmartThings can confirm this is reasonable or add information and then close this issue.

**Comment by gvkalra** [comment]
@CNG :+1:

**Comment by jimmyjames** [comment]
Yep, looks good @CNG. It's a known issue right now that the category actually doesn't control where the app is listed in the mobile client anymore. If you're ok with your change we can close this issue.

**Comment by CNG** [comment]
It's OK by me, though I think @gvkalra can close the issue, not me.
