### ISSUE TITLE
Architecture: typo in graphic

### ISSUE THREAD

**Issue by CNG** [SmartThingsCommunity/Documentation#289]
In [Architecture](https://github.com/SmartThingsCommunity/Documentation/blob/master/architecture/index.rst), the graphic under "Big Picture" contains a box with "Web IU", I assume instead of "Web UI". I noted this as a "todo" in the source code in https://github.com/SmartThingsCommunity/Documentation/pull/288 since I saw another such message referring to the "Big Picture" graphic, so if that is sufficient for it to be fixed at some point, this issue can be closed.

**Comment by jimmyjames** [comment]
I'm going to leave it open for now, because it's good to keep it out here in front of us to address. thanks!
