### ISSUE TITLE
SmartApp Developer's Guide: Example: minor issues

### ISSUE THREAD

**Issue by CNG** [SmartThingsCommunity/Documentation#290]
In [Example: Bon Voyage](http://docs.smartthings.com/en/latest/smartapp-developers-guide/example-bon-voyage.html):
1. In general, the text could be reduced and therefore made clearer by removing "the method" and similar phrases when the method is explicitly referenced.
   - "which is what the `runIn()` method requires" vs. "which `runIn()` requires"
   - "define our `takeAction()` method" vs. "define `takeAction()`"
2. I'm new to Groovy, but from what I surmised about the Groovy Truth from the docs, it seems the following code is not idiomatic:
   
   ```
   (falseAlarmThreshold != null && falseAlarmThreshold != "") ? falseAlarmThreshold : 10
   ```
   
   And perhaps it could be written:
   
   ```
   falseAlarmThreshold ?: 10
   ```
3. This phrase is not clear (to me at least!):
   
   > This is necessary since something may have changed since it was already called…

**Comment by jimmyjames** [comment]
`falseAlaramThreshold ?: 10` would return `10` when the `falseAlarmThreshold` is 0, where the original would return 10 (`0` is considered `false` in Groovy).

The other updates look good though; if you want to make a PR I'm happy to review it, else we can keep this issue open and address it in the future.

Thanks!

**Comment by CNG** [comment]
Ah, of course, you're correct. My pattern recognition was on overdrive since I had just read your ST intro to Groovy in which it showed replacing `myMap != null && !myMap.isEmpty()` with `myMap`, etc.

I'll leave this open for a bit for the other suggestions, which I may have started touching in on my last PR, but I think it could be more succinct in general.
