### ISSUE TITLE
SmartApp Web Services Developer's Guide: possible issue in graphic

### ISSUE THREAD

**Issue by CNG** [SmartThingsCommunity/Documentation#291]
In [Web Services SmartApps Overview](http://docs.smartthings.com/en/latest/smartapp-web-services-developers-guide/overview.html), the graphic under "OAuth-Integrated App Installation Flow" contains two identical boxes with "Install "API Access" SmartApp". Is this intended, or an oversight?

**Comment by jimmyjames** [comment]
No, it's an issue worth keeping open, not intended. 

@unixbeast something we should fix before the end of next week.
