### ISSUE TITLE
SmartApp Developer's Guide: Preferences and Settings image formatting

### ISSUE THREAD

**Issue by CNG** [SmartThingsCommunity/Documentation#292]
In [Preferences & Settings](http://docs.smartthings.com/en/latest/smartapp-developers-guide/preferences-and-settings.html), there is a table under the heading "Multiple Preferences Pages" that seems intended to have three columns, each with an image. The images are displaying huge. It seems this is due to the original author perhaps not being able to get the reStructuredText parser to read the image options (height, width) within the table. I reformatted this in https://github.com/SmartThingsCommunity/Documentation/pull/288 and it previewed OK when I tested on http://rst.ninjs.org/, but it does not look OK in Github's RST preview. Please confirm this fix worked with your own RST parser before making it live in your documentation.

**Comment by jimmyjames** [comment]
Thanks for the change @CNG - your changes are live now [here](http://docs.smartthings.com/en/latest/smartapp-developers-guide/preferences-and-settings.html#multiple-preferences-pages) - looks good, is this what you were expecting?

**Comment by CNG** [comment]
No problem @jimmyjames, it looks good now! Thanks!
