### ISSUE TITLE
Bad link to zigbee cluster library reference material

### ISSUE THREAD

**Issue by jdeltoft** [SmartThingsCommunity/Documentation#41]
There is a bad link at the very bottom of this page:

http://docs.smartthings.com/en/latest/device-type-developers-guide/building-zigbee-device-types/building-zigbee-device-types.html

The bad link points to:

http://www.zigbee.org/Specifications/ZigBee/download.aspx

**Comment by jdeltoft** [comment]
Perhaps this is the right ilnk now:

http://zigbee.org/non-menu-pages/zigbee-cluster-library-specification-download/

**Comment by jimmyjames** [comment]
thanks! fixed now.
