### ISSUE TITLE
Repository Structure: dirs/files need to be lowercase?

### ISSUE THREAD

**Issue by airdrummingfool** [SmartThingsCommunity/Documentation#514]
Are the directories and folders in a SmartThings repository required to be lowercase in order to work with the GitHub integration? I didn't find anything mentioning lowercase [in the docs](http://docs.smartthings.com/en/latest/tools-and-ide/github-integration.html#repository-structure), but I had trouble adding devices and smartapps from a repository (using the "Update from Repo" button) until I lowercased my files.

If they are required to be lowercase, I'm happy to submit a PR to fix the docs - but I wanted to check first.

**Comment by rajkaramchedu** [comment]
@airdrummingfool Thanks for alerting on this. It is a convention SmartThings adopted, namely that the directory/folder names must all be lower case and must "match" the namespace and name of the device handler or smart app, i.e., all lower case with non-alphanumeric characters replaced with a dash. For example, i.e. if a smart app has the namespace "My Apps" and the name "My First App" then the path name for it must be `smartapps/my-apps/my-first-app.src/my-first-app.groovy`. We will update the docs to reflect this.

**Comment by jimmyjames** [comment]
Closed with #516
