### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by artemgurzhii** [SmartThingsCommunity/Documentation#530]
<img width="876" alt="screen shot 2017-01-02 at 04 24 53" src="https://cloud.githubusercontent.com/assets/13109164/21584096/73c34d10-d0a3-11e6-9c6e-7d769fcd9448.png"> Here is [link](https://github.com/SmartThingsCommunity/Documentation/blob/b9a7720c876eb1cbf6cd9eedaddc1dd16c217eda/getting-started/groovy-basics.rst#strings) to the file.

**Comment by jimmyjames** [comment]
closed with #531
