### ISSUE TITLE
ThingShield no longer available for purchase

### ISSUE THREAD

**Issue by mfaulkinbury** [SmartThingsCommunity/Documentation#536]
On this [page](http://docs.smartthings.com/en/latest/arduino/) there is a reference and link to purchasing the ThingShield in the online shop.  When you follow that link, you end up on a product page with no "Add to Cart" button.  After calling support, they indicate that the ThingShield is no longer in distribution.  Please update the referenced page to reduce community friction.

Note: This is probably only one of many links with the same problem.

Best,
Mike

**Comment by jimmyjames** [comment]
Fixed with PR above. Thanks!
