### ISSUE TITLE
addChildDevice syntax changed?

### ISSUE THREAD

**Issue by beckyricha** [SmartThingsCommunity/Documentation#539]
Hi - I had code that worked previously a couple of years ago, but using the same command syntax on the  addChildDevice command in a new SmartApp I am drafting throws an array out of bounds error, no matter what I try (can't test it in the old smartApp for some other reasons - I no loner own/use the type of device that was designed for).  I looked online and saw some similar errors with no solutions, but only in the last few months.  Has something changed in the syntax or something else regarding this feature?

**Comment by rajkaramchedu** [comment]
@beckyricha you might get a helpful response if you post your question over at community forum here: https://community.smartthings.com/

**Comment by beckyricha** [comment]
Thanks. I looked there too. I think i delved it myself, and the command had changed from the documentation. It works, but only IU i directory a hub. In the divinely it says you can have it as null, and shows null in the example code. That no longer allowed to work.  When i included a hub all was well.
Becky
On Jan 12, 2017 3:11 PM, Raj Karamchedu <notifications@github.com> wrote:@beckyricha you might get a helpful response if you post your question over at community forum here: https://community.smartthings.com/
