### ISSUE TITLE
please add state.remove to state documentation.  

### ISSUE THREAD

**Issue by imnotbob** [SmartThingsCommunity/Documentation#617]
It will remove both state or atomicState variables.

**Comment by rajkaramchedu** [comment]
@imnotbob will look into it, thanks!

**Comment by rajkaramchedu** [comment]
Hey, @imnotbob did you mean this? http://docs.smartthings.com/en/latest/smartapp-developers-guide/state.html?highlight=state.remove#removing-values 

Let me know if different. Thanks for the alert :- )

**Comment by imnotbob** [comment]
state.remove works with atomicState also (in my experience), and it removes the value.

**Comment by rajkaramchedu** [comment]
@imnotbob if what you say is the case, then this page needs correction: http://docs.smartthings.com/en/latest/smartapp-developers-guide/state.html?highlight=state.remove#id3

Let me look into it. Thanks.
