### ISSUE TITLE
HubAction NOT Sending Request!

### ISSUE THREAD

**Issue by confusedtoo** [SmartThingsCommunity/Documentation#637]
I'm trying to write a simple API connection to a custom device (ESP8266) that I will use to collect data about motors running and time cycles.  I haven't been able to get "HubAction" or "SendHubCommand" to send "Get"s to a device on my local LAN, I even supplied the IP address to keep it simple.  The Get request just never gets there, tried with both NodeMCU(8266) and Apache server neither indicate any access in the logs.  This Hub (brick) just isn't sending the request out.  Is it just my impression or is this whole "SmartThings" way Overcomplicated?  They say it's supposed to be easy for beginners to program I'm not seeing it here.  I'm not a beginning programmer and I can't send out a simple HTTP request!!! I have the other end the NodeMCU(8266) all programed it reads the ADC and responds via HTTP. It was a simple job to get that all running and flashed! But I can't get this ST Hub to send simple HTTP reqs out???  Something's wrong here and me thinks it's in the beans!!!  Any Ideas?

**Comment by naterh** [comment]
The community.smartthings.com site might get you more the response and info your looking for...

https://community.smartthings.com/t/help-troubleshooting-hubaction/17052
